### ISSUE TITLE
[1.12.1] - net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mekanism

### ISSUE THREAD

**Issue by Protheus** [TheTemportalist/Compression#16]
Gamecrash on loading with latest version of Compression and Mekanism

**Pastebin:** https://pastebin.com/8B5pwWPW
- Compression-1.12.1-1.2.1.jar 
- Forge: 2485
- Mekanism: 326
-----

**Short:**

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mekanism (mekanism)
Caused by: java.lang.IllegalArgumentException: Cannot set property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockPlanks$EnumType, values=[acacia, dark_oak]} to oak on block minecraft:log2, it is not an allowed value
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:227)
    at net.minecraft.block.BlockNewLog.func_176203_a(SourceFile:58)
    at com.temportalist.compression.common.init.CompressedStack.canCompressItem(CompressedStack.java:243)
    at com.temportalist.compression.common.recipes.Recipes$RecipeCompress.isValidInventoryStack(Recipes.java:92)
    at com.temportalist.compression.common.recipes.Recipes$RecipeCompress.getStackAndTier(Recipes.java:116)
    at com.temportalist.compression.common.recipes.Recipes$RecipeCompress.func_77569_a(Recipes.java:149)
    at net.minecraft.item.crafting.CraftingManager.func_192413_b(CraftingManager.java:213)
    at mekanism.common.util.MekanismUtils.findMatchingRecipe(MekanismUtils.java:1385)
    at mekanism.common.integration.OreDictManager.addLogRecipes(OreDictManager.java:328)
    at mekanism.common.integration.OreDictManager.init(OreDictManager.java:37)
    at mekanism.common.Mekanism.postInit(Mekanism.java:820)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:609)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:786)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:348)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-----

**Comment by TheTemportalist** [comment]
I will look into this. It might only be able to be fixed by blacklisting something from Mekanism

**Comment by Protheus** [comment]
Maybe add config option to blacklist mods.

**Comment by TheTemportalist** [comment]
This should be fixed in the next build. It looks like an incompatibility with Mekanism's iteration of possible recipes. So I created a error catching area. Should fix the crash, but the resulting effect is unknown, as I am unaware of Mekanism's usage of the recipe list it creates.
